#!/bin/bash

rsync -a /var/cache/pacman/pkg/ /run/media/sorath/Vault/Archlinux/Pacman
paccache -c /run/media/sorath/Vault/Archlinux/Pacman -rk1
#paccache -c /run/media/sorath/Vault/Archlinux/Pacman -ruk0

cd /run/media/sorath/Vault/Archlinux/Pacman/
rm kore.db
rm kore.db.tar.gz
rm kore.db.tar.gz.old
rm kore.files
rm kore.files.tar.gz
rm kore.files.tar.gz.old

repo-add kore.db.tar.gz ./*.xz
repo-add kore.db.tar.gz ./*.zst
