#!/bin/bash

url=$({
    awk '{ tmp = $1; $1 = $2; $2 = tmp; print $1 }' "$QUTE_CONFIG_DIR"/quickmarks
    sqlite3 -separator ' ' "$QUTE_DATA_DIR"/history.sqlite 'SELECT url, title FROM CompletionHistory' | sort | awk '{print $1}'
    cat "$QUTE_CONFIG_DIR"/bookmarks/urls
} | dmenu -i -fn "UbuntuMono Nerd Font:size=10" -nf "#cccccc" -nb "#292d3e" -sb "#74438e" -sf "#a5bdf7" -l 7 -p "open $* ")

if [ $? = 0 ] && [ -n "$url" ]; then
    printf 'open %s %s\n' "$*" "$url" >>"$QUTE_FIFO"
fi

xdotool key Super_L+Down
