#!/bin/sh
#while read file
#do
# put files in an array
files=()
while IFS= read -r file; do
    file=$(realpath "$file")
    files+=("$file")

        case "$1" in
        "w") setbg "$file" & ;;
        "c")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/directories | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/directories | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"g")	ifinstalled gimp && gimp "$file" & ;;

	"s")
		fname="$(echo "$file" | rev | cut -d "/" -f 1 | rev)"
		cp "$file" "/home/$USER/Imagens" && notify-send -i "$(readlink -f "$file")" "$fname moved to Image folder!" &
                ;;
	"m")
		fname="$(echo "$file" | rev | cut -d "/" -f 1 | rev)"
		cp "$file" "/home/$USER/Transferências/Marcia" && notify-send -i "$(readlink -f "$file")" "$fname moved to Image folder!" &
                ;;
	"x")
			lf -remote "send select '$file'"
			lf -remote "send toggle" ;;
    "Delete" | "d")
        if [ "${#files[@]}" = 1 ]; then
            P=$(basename "$f")
        else
            P="${#files[@]} files"
        fi
        R=$(printf "Trash\nDelete permanently\nCancel" |
                dmenu -p "Delete $P?" -i -sb red -nf red)
        case "$R" in
            Trash)   for f in "${files[@]}"; do trash-put "$f"; done;;
        esac;;
    "Play video" | "p")
        open "${files[@]}";;
        esac
done
